// src/components/BikeData.js

export const SAMPLE_BIKES = [
  {
    id: "b1",
    brand: "Royal Enfield",
    model: "Classic 350",
    price: 185000,
    fuelType: "Petrol",
    img: "/daily_efficient_bikes.jpg",
    mileage: 35,
    displacement: "349 cc",
    power: "20.2 bhp",
    torque: "27 Nm",
    description: "Timeless design meets modern capability. Perfect for city rides and long tours.",
    showroom: [{ name: "Twin Tyres Pune", city: "Pune", phone: "+91-20-xxxxxxx" }],
    upcoming: false,
  },
  {
    id: "b2",
    brand: "TVS",
    model: "iQube",
    price: 139000,
    fuelType: "Electric",
    img: "/efficient_bike.jpg",
    mileage: 105,
    displacement: "—",
    power: "4.4 kW",
    torque: "140 Nm",
    description: "Silent, smooth and efficient urban electric scooter.",
    showroom: [{ name: "RideTVS Chennai", city: "Chennai", phone: "+91-44-xxxxxxx" }],
    upcoming: false,
  },
  {
    id: "b3",
    brand: "Hero",
    model: "Splendor Plus",
    price: 84000,
    fuelType: "Petrol",
    img: "/fast_bike.jpeg",
    mileage: 65,
    displacement: "97.2 cc",
    power: "8.02 bhp",
    torque: "8.05 Nm",
    description: "Reliable daily commuter with excellent fuel efficiency.",
    showroom: [{ name: "Hero Motors Hyderabad", city: "Hyderabad", phone: "+91-40-xxxxxxx" }],
    upcoming: false,
  },
  {
    id: "b4",
    brand: "Yamaha",
    model: "R1 (2026)",
    price: 2500000,
    fuelType: "Petrol",
    img: "/royal&field.jpeg",
    mileage: 18,
    displacement: "998 cc",
    power: "200 bhp",
    torque: "112 Nm",
    description: "Next-gen superbike — arrival expected Q1 2026.",
    showroom: [{ name: "Yamaha Showroom Mumbai", city: "Mumbai", phone: "+91-22-xxxxxxx" }],
    upcoming: true,
  },
  {
    id: "b5",
    brand: "KTM",
    model: "Duke 390",
    price: 280000,
    fuelType: "Petrol",
    img: "/bike2.jpg",
    mileage: 35,
    displacement: "373 cc",
    power: "44 bhp",
    torque: "37 Nm",
    description: "Sporty performance bike suitable for city and highway rides.",
    showroom: [{ name: "KTM Showroom Bangalore", city: "Bangalore", phone: "+91-80-xxxxxxx" }],
    upcoming: false,
  },
  {
    id: "b6",
    brand: "Bajaj",
    model: "Pulsar 150",
    price: 110000,
    fuelType: "Petrol",
    img: "/comfort_bike.webp",
    mileage: 50,
    displacement: "149 cc",
    power: "14 bhp",
    torque: "13.4 Nm",
    description: "Affordable sporty commuter bike with efficient mileage.",
    showroom: [{ name: "Bajaj Showroom Delhi", city: "Delhi", phone: "+91-11-xxxxxxx" }],
    upcoming: false,
  },
  {
    id: "b7",
    brand: "Honda",
    model: "CB Shine",
    price: 95000,
    fuelType: "Petrol",
    img: "/light_weight_bikes.jpeg",
    mileage: 60,
    displacement: "124 cc",
    power: "10.5 bhp",
    torque: "10.3 Nm",
    description: "Smooth and comfortable daily commuter.",
    showroom: [{ name: "Honda Showroom Chennai", city: "Chennai", phone: "+91-44-xxxxxxx" }],
    upcoming: false,
  },
  {
    id: "b8",
    brand: "Upcoming",
    model: "Kawasaki Ninja ZX-10R",
    price: 2000000,
    fuelType: "Electric",
    img: "/olas1.jpg",
    mileage: 15,
    displacement: "998 cc",
    power: "203 bhp",
    torque: "114 Nm",
    description: "High-performance superbike — launch expected Q3 2025.",
    showroom: [{ name: "Kawasaki Showroom Pune", city: "Pune", phone: "+91-20-xxxxxxx" }],
    upcoming: true,
  },
];
